name: Build edk2-rk3399

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential uuid-dev iasl python3-distutils git nasm gcc-aarch64-linux-gnu curl ca-certificates

    - name: Verify GCC 5
      run: |
        gcc-5 --version
        g++-5 --version

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git -b edk2-stable202002 --recursive --depth=1
        git clone https://github.com/tianocore/edk2-platforms.git -o cfdc7f907d545b14302295b819ea078bc36c6a40 --recursive --depth=1
        git clone https://github.com/strongtz/edk2-rk3399

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      env:
        CC: gcc-5
        CXX: g++-5
      run: |
        bash build.sh --device polaris
        mv workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/RK3399_ZMOOTH_UEFI.fd

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: zmooth-edk2
        path: workspace-edk2/edk2-rk3399/workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/RK3399_ZMOOTH_UEFI.fd
        if-no-files-found: ignore
